# Docs for the Azure Web Apps Deploy action: https://github.com/Azure/webapps-deploy
# More GitHub Actions for Azure: https://github.com/Azure/actions

name: Build and deploy container app to Azure Web App - teststdperdocker

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: 'ubuntu-latest'

    steps:
    - uses: actions/checkout@v2

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    - name: Log in to registry
      uses: docker/login-action@v2
      with:
        registry: https://teststdperdocker.azurecr.io/
        username: ${{ secrets.AzureAppService_ContainerUsername_33f404541d504d66bc8b907211658a78 }}
        password: ${{ secrets.AzureAppService_ContainerPassword_307c77cb656243f784d6e15ce5f7b0ee }}

    - name: Build and push container image to registry
      uses: docker/build-push-action@v3
      with:
        push: true
        tags: teststdperdocker.azurecr.io/${{ secrets.AzureAppService_ContainerUsername_33f404541d504d66bc8b907211658a78 }}/stdper:${{ github.sha }}
        file: ./Dockerfile

  deploy:
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: 'production'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}

    steps:
    - name: Deploy to Azure Web App
      id: deploy-to-webapp
      uses: azure/webapps-deploy@v2
      with:
        app-name: 'teststdperdocker'
        slot-name: 'production'
        publish-profile: ${{ secrets.AzureAppService_PublishProfile_d511dbe16cc34ff389413964a5109c97 }}
        images: 'teststdperdocker.azurecr.io/${{ secrets.AzureAppService_ContainerUsername_33f404541d504d66bc8b907211658a78 }}/stdper:${{ github.sha }}'
