# Docs for the Azure Web Apps Deploy action: https://github.com/Azure/webapps-deploy
# More GitHub Actions for Azure: https://github.com/Azure/actions

name: Build and deploy container app to Azure Web App - dockerstdper

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: 'ubuntu-latest'

    steps:
    - uses: actions/checkout@v2

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    - name: Log in to registry
      uses: docker/login-action@v2
      with:
        registry: https://teststdperdocker.azurecr.io/
        username: ${{ secrets.AzureAppService_ContainerUsername_1d873d98c23e4655a5f72c5438525780 }}
        password: ${{ secrets.AzureAppService_ContainerPassword_56aa6ef8f1fa4290accd7ba98a4ae994 }}

    - name: Build and push container image to registry
      uses: docker/build-push-action@v3
      with:
        push: true
        tags: teststdperdocker.azurecr.io/${{ secrets.AzureAppService_ContainerUsername_1d873d98c23e4655a5f72c5438525780 }}/stdper:${{ github.sha }}
        file: ./Dockerfile

  deploy:
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: 'production'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}

    steps:
    - name: Deploy to Azure Web App
      id: deploy-to-webapp
      uses: azure/webapps-deploy@v2
      with:
        app-name: 'dockerstdper'
        slot-name: 'production'
        publish-profile: ${{ secrets.AzureAppService_PublishProfile_e071831c4cff4b06b980a3807bd4fa22 }}
        images: 'teststdperdocker.azurecr.io/${{ secrets.AzureAppService_ContainerUsername_1d873d98c23e4655a5f72c5438525780 }}/stdper:${{ github.sha }}'